using UnityEngine;

namespace Lotec.Lighting {
    /// <summary>
    /// The direction set one bake used, saved as an asset beside that bake's textures.
    ///
    /// This is a SNAPSHOT, not a shared lookup table, and that distinction is the whole point. The
    /// directions are generated by <see cref="Fibonacci"/> from (count, hemisphereOnly), so every bake
    /// with the same settings produces identical values - but pointing several bakes at ONE shared
    /// asset would mean regenerating it (or changing the generator) silently repoints every existing
    /// bake's data at different angles. The texture would still decode; the shadows would just come
    /// from the wrong directions. So: one asset per bake, written by the baker, never hand-authored.
    /// </summary>
    public class VoxelDirectionSet : ScriptableObject {
        [Tooltip("Unit directions this bake sampled, in bake order. Written by the baker - editing " +
                 "these by hand desynchronises them from the baked texture.")]
        public Vector3[] directions;

        public int Count => directions != null ? directions.Length : 0;
    }
}
