#pragma kernel CSComputeRadiance
#pragma kernel CSComputeIrradiance
#pragma kernel CSBlurIrradiance
#pragma kernel CSClearVolume

// --- CONSTANTS ---
// TODO: Use value from Volume conf.
#define MAX_SDF_DIST 30.0
#define EPSILON 0.001

#include "../Includes/Math.hlsl"
#include "../Includes/Volume.hlsl"
#include "../Includes/VoxelSdfShadows.hlsl"
#include "../Includes/Raymarch.hlsl"
#include "../Includes/Fibonacci.hlsl"

// --- RESOURCES ---

// Inputs (Read Only)
Texture3D<float4> _MaterialAlbedoRoughness; // RGB = Albedo, A = Roughness
Texture3D<float4> _MaterialEmissionMetallic; // RGB = Emission, A = Metallic
Texture3D<float> _DistanceField; // Low-res

// GI field buffers
Texture3D<float4> _RadianceField;          // Current Frame Radiance (read in irradiance pass)
RWTexture3D<float4> _RadianceFieldWrite;   // Current Frame Radiance (write in radiance pass)
Texture3D<float4> _IrradianceFieldHistory; // Previous Frame Irradiance (read in both passes)
RWTexture3D<float4> _IrradianceFieldWrite; // Current Frame Irradiance (write in irradiance pass)
Texture3D<float4> _IrradianceFieldInput;   // Temporal irradiance (read in blur pass)
RWTexture3D<float4> _IrradianceFieldFinal; // Final blurred irradiance

// Blue noise for stochastic sampling
Texture2D<float> _BlueNoiseTex;

// Samplers
SamplerState linearClampSampler;
SamplerState pointClampSampler;  // For precise SDF reads

// --- UNIFORMS ---
float3 _RadianceTextureSize;
float3 _VoxelSize;
uint _FrameCount;
uint _MaxSamples;
uint _RaysPerFrame;
float3 _DirectLightDir;
float4 _DirectLightColor;
float3 _SkyColor;

// --- HELPERS ---

float SampleSDF(float3 pos) {
    float3 uvw = WorldToVoxelUV(pos);
    return _DistanceField.SampleLevel(linearClampSampler, uvw, 0).r;
}
// Calculate normal from SDF gradient
float3 GetNormalFromSDF(float3 pos) {
    float2 k = float2(1, -1);
    float3 h = _VoxelSize * 0.1; // Sampling step size
    
    // Tetrahedron technique (efficient gradient calculation)
    return normalize(
        k.xyy * SampleSDF(pos + k.xyy * h) + 
        k.yyx * SampleSDF(pos + k.yyx * h) + 
        k.yxy * SampleSDF(pos + k.yxy * h) + 
        k.xxx * SampleSDF(pos + k.xxx * h)
    );
}

float RaymarchSDF(float3 voxelCenter, float3 rayDir, out float3 hitPos) {
    return RayMarchTex3D(_DistanceField, linearClampSampler, voxelCenter, rayDir, _VolumePosition, _VolumeSize, 0, MAX_SDF_DIST, EPSILON, 0.01, 64, 0.5, hitPos);
}

// --- DEBUG: Clear Kernel ---
RWTexture3D<float4> _ClearTarget;
[numthreads(8,8,8)]
void CSClearVolume(uint3 id : SV_DispatchThreadID)
{
    if (any(id >= uint3(_RadianceTextureSize.xyz))) return;

    _ClearTarget[id] = float4(0.0, 0.0, 0.0, 0.0);
}

// ----------------------------------------------------------
// RADIANCE PASS
// Calculate how much light this voxel emits.
// ----------------------------------------------------------
[numthreads(8, 8, 8)]
void CSComputeRadiance(uint3 id : SV_DispatchThreadID)
{
    if (any(id >= uint3(_RadianceTextureSize.xyz))) return;

    float3 voxelCenter = _VolumePosition + (float3(id) * _VoxelSize) + (_VoxelSize * 0.5);
    float3 uvw = WorldToVoxelUV(voxelCenter);
    float dist = _DistanceField.SampleLevel(pointClampSampler, uvw, 0).r;

    // Only near-surface voxels radiate.
    bool shouldRadiate = dist > 0 && dist <= _VoxelSize.x;
    if (!shouldRadiate) {
        _RadianceFieldWrite[id] = 0;
        return;
    }

    float3 surfacePos = voxelCenter;
    float3 surfaceNormal = GetNormalFromSDF(surfacePos);

    // Get direct sun light. TODO: Optimize by sampling a shadowmap as a crude first step, then only raymarch if needed?
    float3 uvwSurface = WorldToVoxelUV(surfacePos);
    float4 albedoRoughness = _MaterialAlbedoRoughness.SampleLevel(linearClampSampler, uvwSurface, 0);

    // Get indirect light from GI field.
    // Get corner position for more linear interpolation blur.
    float3 irradianceSamplePos = surfacePos + surfaceNormal * (_VoxelSize * 0.5);
    float3 irradianceUVW = WorldToVoxelUV(irradianceSamplePos);
    float3 surfaceIrradiance = _IrradianceFieldHistory.SampleLevel(linearClampSampler, irradianceUVW, 0).rgb;

    float3 sunStart = surfacePos + surfaceNormal * (_VoxelSize * 0.1);
    float3 hitPos;
    // In most cases visibility is 0 or 1, but in shadow edge cases it can be fractional like 0.1 when ray almost hits a surface. This adds softness to shadow edges.
    float sunVisibility = RaymarchSDF(sunStart, _DirectLightDir, hitPos);
    float3 sunLight = _DirectLightColor.rgb * sunVisibility;
    // TODO: Support another direct light source, like a flashlight.

    // Radiate incoming light (sun + indirect) modulated by surface albedo and roughness.
    // TODO: Modulate by roughness and light direction. 0 roughness = 100% reflection * (N.L).
    // float3 outgoingLight = (surfaceIrradiance + sunLight) * (albedoRoughness.rgb * LOTEC_MATH_INV_PI);
    float3 outgoingLight = (surfaceIrradiance + sunLight) * (albedoRoughness.rgb);
    _RadianceFieldWrite[id] = float4(outgoingLight, 1.0);
}

// ----------------------------------------------------------
// IRRADIANCE PASS
// How much light is arriving at this voxel.
// ----------------------------------------------------------
[numthreads(8, 8, 8)]
void CSComputeIrradiance(uint3 id : SV_DispatchThreadID)
{
    if (any(id >= uint3(_RadianceTextureSize.xyz))) return;

    float3 voxelCenter = _VolumePosition + (float3(id) * _VoxelSize) + (_VoxelSize * 0.5);
    float3 uvw = WorldToVoxelUV(voxelCenter);
    // Abort if inside geometry.
    if (_DistanceField.SampleLevel(pointClampSampler, uvw, 0).r <= 0) return;

    // Shoot cosine-weighted rays aligned to the surface normal.
    float3 incomingLight = float3(0, 0, 0);
    float3 surfaceNormal = GetNormalFromSDF(voxelCenter);
    uint rayCount = max(_RaysPerFrame, 1u);

    [loop]
    for (uint rayIndex = 0u; rayIndex < rayCount; rayIndex++) {
        float2 noise2 = GetBlueNoise2(_BlueNoiseTex, id, _FrameCount, rayIndex);
        float3 rayDir = CosineSampleHemisphere(surfaceNormal, noise2);

        float3 hitPos;
        float lit = RaymarchSDF(voxelCenter, rayDir, hitPos);
        if (lit == 0) {
            // Sample value half a voxel away from the surface hit point, to avoid sampling a voxel center inside the surface.
            float3 surfaceUVW = WorldToVoxelUV(hitPos - rayDir * _VoxelSize * 0.51);
            incomingLight += _RadianceField.SampleLevel(linearClampSampler, surfaceUVW, 0).rgb;
        } else {
            // No hit means we get sky light.
            incomingLight += _SkyColor;
        }
    }

    incomingLight *= rcp((float)rayCount);

    float4 history = _IrradianceFieldHistory.Load(int4(id, 0));
    float3 oldColor = history.rgb;
    // Hysteresis blend: fast-in for brightening, slow-out for darkening. Maybe for flashlight?
    // float newLuma = Luminance(incomingLight);
    // float historyLuma = Luminance(oldColor);
    // float weight = (newLuma > historyLuma) ? 0.25 : 0.01;
    float weight = 1.0f / _MaxSamples;
    float3 finalColor = lerp(oldColor, incomingLight, weight);

    _IrradianceFieldWrite[id] = float4(finalColor, 1.0);
}

// ----------------------------------------------------------
// SPATIAL BLUR PASS
// Turbo 8-tap blur: sample voxel corners with linear sampling.
// ----------------------------------------------------------
[numthreads(8, 8, 8)]
void CSBlurIrradiance(uint3 id : SV_DispatchThreadID)
{
    if (any(id >= uint3(_RadianceTextureSize.xyz))) return;

    float3 voxelCenter = _VolumePosition + (float3(id) * _VoxelSize) + (_VoxelSize * 0.5);
    float3 uvwCenter = WorldToVoxelUV(voxelCenter);
    float3 uvwHalf = (_VoxelSize * 0.5) * rcp(max(_VolumeSize, 1e-6));

    float3 sum = 0.0;
    sum += _IrradianceFieldInput.SampleLevel(linearClampSampler, uvwCenter + float3(-uvwHalf.x, -uvwHalf.y, -uvwHalf.z), 0).rgb;
    sum += _IrradianceFieldInput.SampleLevel(linearClampSampler, uvwCenter + float3( uvwHalf.x, -uvwHalf.y, -uvwHalf.z), 0).rgb;
    sum += _IrradianceFieldInput.SampleLevel(linearClampSampler, uvwCenter + float3(-uvwHalf.x,  uvwHalf.y, -uvwHalf.z), 0).rgb;
    sum += _IrradianceFieldInput.SampleLevel(linearClampSampler, uvwCenter + float3( uvwHalf.x,  uvwHalf.y, -uvwHalf.z), 0).rgb;
    sum += _IrradianceFieldInput.SampleLevel(linearClampSampler, uvwCenter + float3(-uvwHalf.x, -uvwHalf.y,  uvwHalf.z), 0).rgb;
    sum += _IrradianceFieldInput.SampleLevel(linearClampSampler, uvwCenter + float3( uvwHalf.x, -uvwHalf.y,  uvwHalf.z), 0).rgb;
    sum += _IrradianceFieldInput.SampleLevel(linearClampSampler, uvwCenter + float3(-uvwHalf.x,  uvwHalf.y,  uvwHalf.z), 0).rgb;
    sum += _IrradianceFieldInput.SampleLevel(linearClampSampler, uvwCenter + float3( uvwHalf.x,  uvwHalf.y,  uvwHalf.z), 0).rgb;

    _IrradianceFieldFinal[id] = float4(sum * 0.125f, 1.0);
}
